---
title: "A Visual Approach to Shootings Recorded by NYPD"
author: "Jeremy Zhang, Christopher Pei"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction to Data

Our data is obtainedfrom https://catalog.data.gov/dataset/nypd-arrest-data-year-to-date. 

```{r}
library(tidyverse)
data <- read_csv("./NYPD_Shooting_Incident_Data__Historic_.csv")
```

Briefly talk about the variables: types, values...

```{r}
summary(data)
```

## Data Cleaning

```{r}
cleaned_data <- data

cleaned_data <- cleaned_data %>%
  mutate(OCCUR_DATE = as.Date(OCCUR_DATE, format = "%m/%d/%Y"))
```

```{r}
# Check possible values
unique(cleaned_data$BORO) # Looks Fine
```

```{r}
# Check possible values
unique(cleaned_data$PERP_AGE_GROUP)

# Formatize "Unknown" and unexpected values
cleaned_data <- cleaned_data %>%
  mutate(PERP_AGE_GROUP = na_if(PERP_AGE_GROUP, "UNKNOWN")) %>% 
  mutate(PERP_AGE_GROUP = na_if(PERP_AGE_GROUP, "(null)")) %>% 
  mutate(PERP_AGE_GROUP = na_if(PERP_AGE_GROUP, "940")) %>% 
  mutate(PERP_AGE_GROUP = na_if(PERP_AGE_GROUP, "224")) %>% 
  mutate(PERP_AGE_GROUP = na_if(PERP_AGE_GROUP, "1020"))

# Check results
unique(cleaned_data$PERP_AGE_GROUP)
```

```{r}
# Check possible values
unique(cleaned_data$PERP_SEX)

# Formatize "Unknown" and unexpected values
cleaned_data <- cleaned_data %>%
  mutate(PERP_SEX = na_if(PERP_SEX, "(null)")) %>% 
  mutate(PERP_SEX = na_if(PERP_SEX, "U")) # Historically, the U (Unspecified) column has been misused. Therefore we classify as NA

# Check results
unique(cleaned_data$PERP_SEX)
```

```{r}
# Check possible values
unique(cleaned_data$PERP_RACE)

# Formatize "Unknown" and unexpected values
cleaned_data <- cleaned_data %>%
  mutate(PERP_RACE = na_if(PERP_RACE, "UNKNOWN")) %>% 
  mutate(PERP_RACE = na_if(PERP_RACE, "(null)")) %>% 
  mutate(PERP_RACE = recode(PERP_RACE, # To avoid excessively long variable names in visualizations and leading to overlaps
                            "BLACK HISPANIC" = "BLK HISP",
                            "WHITE HISPANIC" = "WHT HISP",
                            "ASIAN / PACIFIC ISLANDER" = "AAPI",
                            "AMERICAN INDIAN/ALASKAN NATIVE" = "NATIVE AM"))

# Check results
unique(cleaned_data$PERP_RACE)
```

```{r}
# Check possible values
unique(cleaned_data$VIC_AGE_GROUP)

# Formatize "Unknown" and unexpected values
cleaned_data <- cleaned_data %>%
  mutate(VIC_AGE_GROUP = na_if(VIC_AGE_GROUP, "UNKNOWN")) %>% 
  mutate(VIC_AGE_GROUP = na_if(VIC_AGE_GROUP, "1022")) 

# Check results
unique(cleaned_data$VIC_AGE_GROUP)
```

```{r}
# Check possible values
unique(cleaned_data$VIC_SEX)

# Formatize "Unknown" and unexpected values
cleaned_data <- cleaned_data %>%
  mutate(VIC_SEX = na_if(VIC_SEX, "U"))

# Check results
unique(cleaned_data$VIC_SEX)
```

```{r}
# Check possible values
unique(cleaned_data$VIC_RACE)

# Formatize "Unknown" and unexpected values
cleaned_data <- cleaned_data %>%
  mutate(VIC_RACE = na_if(VIC_RACE, "UNKNOWN")) %>% 
  mutate(VIC_RACE = recode(VIC_RACE, # To avoid excessively long variable names in visualizations and leading to overlaps
                            "BLACK HISPANIC" = "BLK HISP",
                            "WHITE HISPANIC" = "WHT HISP",
                            "ASIAN / PACIFIC ISLANDER" = "AAPI",
                            "AMERICAN INDIAN/ALASKAN NATIVE" = "NATIVE AM"))

# Check results
unique(cleaned_data$VIC_RACE)
```

## Initial Exploration with Visualization

```{r}
ggplot(cleaned_data, aes(x = VIC_AGE_GROUP)) + 
  labs(title=("NYPD-Recorded Shooting Vitcims by Age Group"),
       x="Age Groups",
       y="Count") + 
  geom_bar()
```

```{r}
ggplot(cleaned_data, aes(x = VIC_RACE)) + 
  labs(title=("NYPD-Recorded Shooting Vitcims by Race"),
       x="Race",
       y="Count") + 
  geom_bar()
```

## Yearly Trends
```{r}
cleaned_data <- cleaned_data %>%
  mutate(OCCUR_YEAR = as.numeric(format(OCCUR_DATE, "%Y")))

yearly_counts <- cleaned_data %>%
  group_by(OCCUR_YEAR) %>%
  summarise(COUNT = n())

ggplot(yearly_counts, aes(x = OCCUR_YEAR, y = COUNT)) +
  geom_line() +
  geom_point() +
  geom_text(aes(label = COUNT), vjust = -0.5) + 
  labs(title = "Number of NYPD-Recorded Shootings by Year",
       x = "Year",
       y = "Count")
```
